### ISSUE TITLE
get_iplayer being retry blocked

### ISSUE THREAD

**Issue by BlackwidowLXXIII** [SquarePenguin101/www.squarepenguin.co.uk#1]
Episodes:
Newsnight - 23/07/2020, BBC Two, m000l447
INFO: 1 total programmes

WARNING: A UK TV licence is required to access BBC iPlayer TV content legally
INFO: Downloading tv: 'Newsnight - 80. 23/07/2020 (m000l447) [original]'

INFO: Downloaded: 0.00 MB (00:00:00) @ 0.00 Mb/s (hvfhd1/bi) [audio+video]
WARNING: Unexpected size for file segment [1]
WARNING: Expected: 5414776  Downloaded: 64447
WARNING: This indicates a problem with your network connection to the media server
WARNING: No streams available for 'original' version (m000l444) - skipping (retry)

Recording complete

get_iplayer Web PVR Manager 3.26.0-MSWin32-x64, ©2009-2010 Phil Lewis - Licensed under GPLv3

this started 2  days ago, and is stopping all attempts to download, newest release is also affected, for some reason it seems the rerequest isn't using the same ID

**Comment by SquarePenguin101** [comment]
I'm curious as to what made you raise an issue here? This is the repo for the guides section of the tutorial site. You'd be better off going to the actual get_iplayer repo or the mailing list if you want help with get_iplayer.

**Comment by BlackwidowLXXIII** [comment]
raised here, as it was the only place I could find to hopefully get your, or another G_iP mods attention, to get the proper place for a bug report, though I thought this was a G_iP area XD thank you :D deal with this as you see fit
